### ISSUE TITLE
Timesheet Issue 1

### ISSUE THREAD

**Issue by WalkerBuilders** [bitg-co/walkergroup-issues#2]
Change the view screen to show date and time by hiding billable hours and deductions

**Comment by brandc87** [comment]
An update has been pushed for an improved view on the table. Please review.

<img width="1475" alt="Screenshot 2020-11-09 at 16 28 52" src="https://user-images.githubusercontent.com/11300674/98568300-dcd92300-22a8-11eb-850b-943ba724433b.png">

**Comment by WalkerBuilders** [comment]
View has changed and working as we requested.

**Comment by DonnaMBee** [comment]
Walker group confirmed acceptance
