### ISSUE TITLE
Timesheet Issue 2

### ISSUE THREAD

**Issue by WalkerBuilders** [bitg-co/walkergroup-issues#3]
Change Priceworks field if easier for Carl also. We only need it to work like the bonus can even be same box called Bonus/Pricework

**Comment by brandc87** [comment]
Pricedwork has been removed and all calculations reverted. The system now only has the bonus field, hours and bonus are calculated in totals.

Please review both admin area and staff areas.

**Comment by WalkerBuilders** [comment]
Bonus/pricework field appears to be calculating correctly

**Comment by DonnaMBee** [comment]
Walker group confirmed acceptance
