### ISSUE TITLE
Materials returns completed and needs review

### ISSUE THREAD

**Issue by brandc87** [bitg-co/walkergroup-issues#8]
The materials returns has been pushed to the live server and needs reviewing by Walker group

**Comment by WalkerBuilders** [comment]
I have asked some of the lads to trial/demo and to give me their feedback. 

My only initial view that I can see if the admin side when it comes through to me, even if added all as part of the same material return they are coming through as separate entries. It would work better to be shown as one document that clicks into then displays all the separate entries for that specific job reference (and all return templates to be linked) if that makes sense?

I will email an example of some of the returns I get which come via email as one document so it links all different returns and entries together which means the data can be processed all in one go. If they were to come through separate entries as they are with 10+ site agents submitting them they would all become mixed up and would significantly increase the time in extracting this information to allocate correctly. EG this morning i received, 15 different jobs all with approx 20 different entries each from 8 different site agents, I tackle this a job at a time. If they were all inputting this information at the same time every entry would become mixed in a long list and i'd likely miss data. These jobs were from thurs/fri of last week. 

Thank you,

**Comment by brandc87** [comment]
Hi Jade,

I have added some filters to the admin area that should let you see specific returns instead of all of them at once, I think the filter includes week ending and project but will double check.

**Comment by WalkerBuilders** [comment]
Hi Carl/Donna,

Two filters have now appeared however both are date related and i can't see a project reference one currently. As noted above i have asked some of the site agents to trial this week however its difficult for them to sort straight away as they are on sites, however I was able to trial on the computer and my only issues were as above to be looked into, 1 site agent submitted a return which has done the same thing come through as three separate entries but also the prices haven't come through despite him putting these in (this didn't happen when i trialed from the computer) therefore awaiting further submissions to see if they have the same issue.

**Comment by WalkerBuilders** [comment]
Hi Carl,

I've just rung another site agent and asked them to submit one while on the phone, they put £100 & £160 on however these have come through as £0 on the admin side to me.

**Comment by DonnaMBee** [comment]
Morning Jade,

I hope you are well and had a good Christmas & New Year.

Could you please provide me with an update on the testing.

Thank you
Regards
Donna

**Comment by WalkerBuilders** [comment]
Hi Donna,

Hope you are well also. 

I am waiting for updates from yourselves following my comments above before Christmas.

To confirm my queries were:
Material returns - no value is coming through when submitted despite this being entered
The project reference filter not showing as described above
View/Display for returns (not all entries are linking to one return which means when they come through to me it would be a long list of single entries and mixing all jobs up which would be time consuming) All entries submitted in one go need to produce 1 single return. 
Timesheet - looking into the admin error for last weeks breakdown 

Jade

**Comment by brandc87** [comment]
Hi Jade,

The value not coming through should be fixed, the issue was a value being entered as "£55.50" instead of "55.50" - I have added a check for this and will show an error if a user adds the £.

Project filter should be visible now.

With the above filter you should be able to narrow down the entries by week ending, order date and project which should narrow down the list you are seeing. The only way to get them grouped is to rewrite the system and use a different approach which would require the projects being created and entries being linked to a project (similar to the timesheets).

I can create a lens that groups all entries by the project and then can sum the cost and how many returns that project has.

Still looking into this as the same problem may occur in the materials return lens if you decide on that route.

**Comment by WalkerBuilders** [comment]
Hi Carl,

Thank you, sorted the value now we've tried it with and without the £ and the value error is showing, thank you.

I can now see the project filter - will wait to see a few samples come in this week to check it filters how i need this too.

Thank you.

**Comment by WalkerBuilders** [comment]
Hi Carl,

I have managed to get the time sheets project filter to work, the only difficulty i am having its a long list of all variations of codes that you have to scroll through it doesn't allow you to type to search, I only noticed this as i couldn't find the code i wanted to search for so couldn't use this filter. 
Material returns, the week ending filter isn't working as its not linking the w/e being the sunday you have to search each day individually so would depend when they've sent them in etc. 

Thank you.

**Comment by brandc87** [comment]
Hi Jade,

There should be a text search for material returns now on the project field. The week ending seems to be working okay here, if I enter 10/01/2021 it returns the two entries from Ashley. Is this not correct?

Thanks Carl

On 15 Jan 2021, at 14:35, WalkerBuilders <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Carl,

I have managed to get the time sheets project filter to work, the only difficulty i am having its a long list of all variations of codes that you have to scroll through it doesn't allow you to type to search, I only noticed this as i couldn't find the code i wanted to search for so couldn't use this filter.
Material returns, the week ending filter isn't working as its not linking the w/e being the sunday you have to search each day individually so would depend when they've sent them in etc.

Thank you.

**Comment by WalkerBuilders** [comment]
Hi Carl, It does, but there is also another entry from yourself on the 7/1/21 which doesnt show but this is part of the same W/E 10th January. So you have to check each day individually rather than W/E if that makes sense

**Comment by brandc87** [comment]
Hi Jade,

Those entries were just testing the system and typically you wouldn’t have a W/E date set in the middle of the week, it would always be a single date. You wouldn’t have a range of dates for week ending on the returns would you?

Thanks Carl

On 25 Jan 2021, at 16:22, WalkerBuilders <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Carl, It does, but there is also another entry from yourself on the 7/1/21 which doesnt show but this is part of the same W/E 10th January. So you have to check each day individually rather than W/E if that makes sense

**Comment by WalkerBuilders** [comment]
![M Sunderland - 17BF3EE8-22E3-4A08-8EDD-513051ABE595](https://user-images.githubusercontent.com/74195648/106273809-2a6f8700-622b-11eb-9e88-f0012429cb92.png)
Hi Carl, 

The week ending will always be the Sunday, like with the returns. the problem we are incurring is when you select week ending (sunday) it only brings up entries with that date on it not entries for that full week. 

I have attached an example of a return, this return has been done weekly, but you can see there are different dates and different suppliers therefore these would currently only show on the system on the date they specify. I need these all to link together when specifying week ending so it pulls through 1 material return with all these entries. If i had to check each project for every day to see if there was any submissions its of a long process, this is quite a small job, some jobs can have 20 + orders and suppliers on different dates within a week

Last week we worked on 46 different jobs altogether so to check each day for materials for each job, then when working properly with internal and external plant it would be very time consuming and a lot of going back and forward between projects when i am extracting that information for our other softwares.

**Comment by WalkerBuilders** [comment]
Hi Carl,

Any update on these?

**Comment by brandc87** [comment]
Hi Jade,

I have just recreated the example you sent through above on the system, when I select the week ending 17/01/2020 it pulls through the orders as expected even though order dates and suppliers are different. The order date filer will only return orders on that date but I could look into making this a range? But week ending seems to be working as expected?

**Comment by WalkerBuilders** [comment]
HI Carl,

Looks like this might work now, an additional week ending feature has appeared so aslong as they put the sunday that should be fine. I'll get them to trial again. Thank you.

**Comment by brandc87** [comment]
Hi Jade,

Are the filters and views giving you enough control over the information you need to see?

Thanks Carl

**Comment by WalkerBuilders** [comment]
Hi Carl,

The filters seem to do this now thank you, however the material return layout has now changed. Before they had to put the generic job details in initially and they could then add multiple entries on this. Whereas now they have to re-input the site information for every entry. I've been given the feedback they preferred how it was originally as it's taking them longer to produce as they are repeating the same details multiple times. Thank you.

**Comment by DonnaMBee** [comment]
Hi Jade,

I’ll ask Carl to look at this – it’s strange as no changes have been made to this since January

Regards
Donna

**Comment by WalkerBuilders** [comment]
Hi Donna,

I might've fixed it now, i just thought it seemed to be those who were set as admins also. I have changed them back now and it seems to be okay. (it was when viewing from admin side, which only a few of them need to be able to do) so i can make sure they are viewing from the right access side.

**Comment by DonnaMBee** [comment]
Hi Jade,

That’s good.

There are risks with giving people Admin access, please be aware that your data isn’t being backed up so if anything goes wrong it will be lost (unless you are keeping copies)

Regards
Donna

**Comment by brandc87** [comment]
Approved by Walker group and closed.
